<?php
/* This code dynamically generates a web page containing a form designed with the html required to display one
checkbox for each of the records currently held in the nmc_records database table has been provided for you in the
assessment section for the module on blackboard. The user can select one or more records that they are interested in
ordering by clicking the checkboxes.
Use the browser to look at the structure of the html generated by the php code. */

require_once('functions.php');  // includes function list file
getSession();   //start of session
echo makePageStart("North Events: Booking", "style.css");   //calls functions from the and dynamically creates sections of the page
echo makeHeader("Northern Events: Booking");
if (isset($_SESSION['logged-in']) && $_SESSION['logged-in']) {  //checks the login status
    echo makeNavMenu(array("index.php" => "Home", "bookEventsForm.php" => "Events", "admin.php" => "Admin", "credits.php" => "Credits"));   //when logged in will display the link to the admin page
    echo loginForm();   //calls function and creates logout link
}
else{
    echo makeNavMenu(array("index.php" => "Home", "bookEventsForm.php" => "Events", "credits.php" => "Credits"));
    echo loginForm();   //calls function and creates login form
}
echo startMain();   //start of the main tag

$url = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/bookEventsFormInc.php";
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($curl);
curl_close($curl);
echo $result;
?>

<script src="functions.js"> //start of script tag with link to javascript functions file
</script>

<?php
echo endMain(); //end of the main tag
echo makeFooter("Designed by Sam Johnston - W17004648");
echo makePageEnd(); //end of the page